// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.4.0
// source: src/ws_allocator/allocator.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Priority int32  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *ConnectionReq) Reset() {
	*x = ConnectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionReq) ProtoMessage() {}

func (x *ConnectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionReq.ProtoReflect.Descriptor instead.
func (*ConnectionReq) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectionReq) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ConnectionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response bool `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ConnectionRes) Reset() {
	*x = ConnectionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRes) ProtoMessage() {}

func (x *ConnectionRes) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRes.ProtoReflect.Descriptor instead.
func (*ConnectionRes) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionRes) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

type AllocReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *AllocReq) Reset() {
	*x = AllocReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocReq) ProtoMessage() {}

func (x *AllocReq) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocReq.ProtoReflect.Descriptor instead.
func (*AllocReq) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{2}
}

func (x *AllocReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AllocRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessDuration int32 `protobuf:"varint,1,opt,name=process_duration,json=processDuration,proto3" json:"process_duration,omitempty"`
	PollDuration    int32 `protobuf:"varint,2,opt,name=poll_duration,json=pollDuration,proto3" json:"poll_duration,omitempty"`
	Response        bool  `protobuf:"varint,3,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *AllocRes) Reset() {
	*x = AllocRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocRes) ProtoMessage() {}

func (x *AllocRes) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocRes.ProtoReflect.Descriptor instead.
func (*AllocRes) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{3}
}

func (x *AllocRes) GetProcessDuration() int32 {
	if x != nil {
		return x.ProcessDuration
	}
	return 0
}

func (x *AllocRes) GetPollDuration() int32 {
	if x != nil {
		return x.PollDuration
	}
	return 0
}

func (x *AllocRes) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

type ReleaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId    string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ProcessDone bool   `protobuf:"varint,2,opt,name=process_done,json=processDone,proto3" json:"process_done,omitempty"`
}

func (x *ReleaseReq) Reset() {
	*x = ReleaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReq) ProtoMessage() {}

func (x *ReleaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReq.ProtoReflect.Descriptor instead.
func (*ReleaseReq) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReleaseReq) GetProcessDone() bool {
	if x != nil {
		return x.ProcessDone
	}
	return false
}

type ReleaseRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PollDuration int32 `protobuf:"varint,1,opt,name=poll_duration,json=pollDuration,proto3" json:"poll_duration,omitempty"`
	Response     bool  `protobuf:"varint,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ReleaseRes) Reset() {
	*x = ReleaseRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRes) ProtoMessage() {}

func (x *ReleaseRes) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRes.ProtoReflect.Descriptor instead.
func (*ReleaseRes) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseRes) GetPollDuration() int32 {
	if x != nil {
		return x.PollDuration
	}
	return 0
}

func (x *ReleaseRes) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

type AllocReq_CpuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NCores int32 `protobuf:"varint,2,opt,name=n_cores,json=nCores,proto3" json:"n_cores,omitempty"`
}

func (x *AllocReq_CpuReq) Reset() {
	*x = AllocReq_CpuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocReq_CpuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocReq_CpuReq) ProtoMessage() {}

func (x *AllocReq_CpuReq) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocReq_CpuReq.ProtoReflect.Descriptor instead.
func (*AllocReq_CpuReq) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AllocReq_CpuReq) GetNCores() int32 {
	if x != nil {
		return x.NCores
	}
	return 0
}

type AllocReq_GpuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NCores  int32 `protobuf:"varint,3,opt,name=n_cores,json=nCores,proto3" json:"n_cores,omitempty"`
	MemSize int32 `protobuf:"varint,4,opt,name=mem_size,json=memSize,proto3" json:"mem_size,omitempty"`
}

func (x *AllocReq_GpuReq) Reset() {
	*x = AllocReq_GpuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocReq_GpuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocReq_GpuReq) ProtoMessage() {}

func (x *AllocReq_GpuReq) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocReq_GpuReq.ProtoReflect.Descriptor instead.
func (*AllocReq_GpuReq) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{2, 1}
}

func (x *AllocReq_GpuReq) GetNCores() int32 {
	if x != nil {
		return x.NCores
	}
	return 0
}

func (x *AllocReq_GpuReq) GetMemSize() int32 {
	if x != nil {
		return x.MemSize
	}
	return 0
}

type AllocReq_MemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemSize int32 `protobuf:"varint,5,opt,name=mem_size,json=memSize,proto3" json:"mem_size,omitempty"`
}

func (x *AllocReq_MemReq) Reset() {
	*x = AllocReq_MemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_ws_allocator_allocator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocReq_MemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocReq_MemReq) ProtoMessage() {}

func (x *AllocReq_MemReq) ProtoReflect() protoreflect.Message {
	mi := &file_src_ws_allocator_allocator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocReq_MemReq.ProtoReflect.Descriptor instead.
func (*AllocReq_MemReq) Descriptor() ([]byte, []int) {
	return file_src_ws_allocator_allocator_proto_rawDescGZIP(), []int{2, 2}
}

func (x *AllocReq_MemReq) GetMemSize() int32 {
	if x != nil {
		return x.MemSize
	}
	return 0
}

var File_src_ws_allocator_allocator_proto protoreflect.FileDescriptor

var file_src_ws_allocator_allocator_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x72, 0x63, 0x2f, 0x77, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x2f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x77, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x48, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x2b, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x6f,
	0x63, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x1a, 0x21, 0x0a, 0x06, 0x43, 0x70, 0x75, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x43,
	0x6f, 0x72, 0x65, 0x73, 0x1a, 0x3c, 0x0a, 0x06, 0x47, 0x70, 0x75, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6e, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x53, 0x69,
	0x7a, 0x65, 0x1a, 0x23, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x65, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x76, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x6f, 0x63,
	0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x6f, 0x6c, 0x6c, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6f, 0x6c, 0x6c, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x4c, 0x0a, 0x0a, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x6f, 0x6e, 0x65, 0x22, 0x4d, 0x0a,
	0x0a, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70,
	0x6f, 0x6c, 0x6c, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x70, 0x6f, 0x6c, 0x6c, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe8, 0x01, 0x0a,
	0x12, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b,
	0x2e, 0x77, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x73,
	0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0f, 0x41, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x2e,
	0x77, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x77, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x46, 0x0a, 0x0e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x12, 0x18, 0x2e, 0x77, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x77, 0x73,
	0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_ws_allocator_allocator_proto_rawDescOnce sync.Once
	file_src_ws_allocator_allocator_proto_rawDescData = file_src_ws_allocator_allocator_proto_rawDesc
)

func file_src_ws_allocator_allocator_proto_rawDescGZIP() []byte {
	file_src_ws_allocator_allocator_proto_rawDescOnce.Do(func() {
		file_src_ws_allocator_allocator_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_ws_allocator_allocator_proto_rawDescData)
	})
	return file_src_ws_allocator_allocator_proto_rawDescData
}

var file_src_ws_allocator_allocator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_src_ws_allocator_allocator_proto_goTypes = []interface{}{
	(*ConnectionReq)(nil),   // 0: ws_allocator.ConnectionReq
	(*ConnectionRes)(nil),   // 1: ws_allocator.ConnectionRes
	(*AllocReq)(nil),        // 2: ws_allocator.AllocReq
	(*AllocRes)(nil),        // 3: ws_allocator.AllocRes
	(*ReleaseReq)(nil),      // 4: ws_allocator.ReleaseReq
	(*ReleaseRes)(nil),      // 5: ws_allocator.ReleaseRes
	(*AllocReq_CpuReq)(nil), // 6: ws_allocator.AllocReq.CpuReq
	(*AllocReq_GpuReq)(nil), // 7: ws_allocator.AllocReq.GpuReq
	(*AllocReq_MemReq)(nil), // 8: ws_allocator.AllocReq.MemReq
}
var file_src_ws_allocator_allocator_proto_depIdxs = []int32{
	0, // 0: ws_allocator.WorkStationService.Connect:input_type -> ws_allocator.ConnectionReq
	2, // 1: ws_allocator.WorkStationService.AllocateMachine:input_type -> ws_allocator.AllocReq
	4, // 2: ws_allocator.WorkStationService.ReleaseMachine:input_type -> ws_allocator.ReleaseReq
	1, // 3: ws_allocator.WorkStationService.Connect:output_type -> ws_allocator.ConnectionRes
	3, // 4: ws_allocator.WorkStationService.AllocateMachine:output_type -> ws_allocator.AllocRes
	5, // 5: ws_allocator.WorkStationService.ReleaseMachine:output_type -> ws_allocator.ReleaseRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_ws_allocator_allocator_proto_init() }
func file_src_ws_allocator_allocator_proto_init() {
	if File_src_ws_allocator_allocator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_ws_allocator_allocator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocReq_CpuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocReq_GpuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_ws_allocator_allocator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocReq_MemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_ws_allocator_allocator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_ws_allocator_allocator_proto_goTypes,
		DependencyIndexes: file_src_ws_allocator_allocator_proto_depIdxs,
		MessageInfos:      file_src_ws_allocator_allocator_proto_msgTypes,
	}.Build()
	File_src_ws_allocator_allocator_proto = out.File
	file_src_ws_allocator_allocator_proto_rawDesc = nil
	file_src_ws_allocator_allocator_proto_goTypes = nil
	file_src_ws_allocator_allocator_proto_depIdxs = nil
}
